version: "3"
services:
  notebook:
    image: footystars-ml:latest
    container_name: footy-py
    build:
      context: ./srv
    env_file:
      - ./srv/.env
    ports:
      - 8000:8000
      - 8888:8888
    volumes:
      - ./srv:/home/jovyan/work
