FROM jupyter/minimal-notebook

# Install Python 3 packages

RUN pip install --upgrade pip \
    web3==6.9.0 \
    python-dotenv==1.0.0
    # Install production dependencies.
#RUN pip install -r requirements.txt